### ISSUE TITLE
is not running against files properly

### ISSUE THREAD

**Issue by alirezabashyri** [reviewdog/action-reek#1]
reek doesn't run against files in github actions while in local machine it returns the errors.

```
reek --single-line | reviewdog -f=reek -diff="git diff develop"
```

**Comment by mgrachev** [comment]
Yes, you are right. I started this action, but have not finished yet 😞 

It would be great if you help me with this problem and we would finish this action together.
What do you think?

**Comment by alirezabashyri** [comment]
I've fixed just now, it seems `reek` pipeline doesn't work like the other tools, I've provided file paths and it worked 

```yaml
  reek:
    name: runner / reek
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: reek
        uses: mgrachev/action-reek@v0.1.6
        with:
          github_token: ${{ secrets.github_token }}
          reek_flags: app/**/*.rb
          reporter: github-pr-review # Default is github-pr-check
```
