### ISSUE TITLE
Large reek output causes reek check to spin forever

### ISSUE THREAD

**Issue by dnorth98** [reviewdog/action-reek#6]
Running the reek action and it seems if reek has a large amount of output, the runner action will complete but the posted result will sit in the "pending" state forever.

I'm pretty sure it's related to this message from the runner

```5 gems installed
reviewdog: post failed for reek: failed to post result: PATCH https://api.github.com/repos/ACME/MY-REPO/check-runs/918892721: 422 Invalid request.

Only 65535 characters are allowed; 104394 were supplied. []
```

I think what happens is the result gets created but because the post fails, it never completes which leaves the check in a forever pending state

Here's our reek action config

```yaml
  reek:
    name: runner / reek
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: reek
        uses: reviewdog/action-reek@v1
        with:
          reek_version: 6.0.1
          github_token: ${{ secrets.github_token }}
          filter_mode: file
```
